---
abstract: 'perl builder'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Build
no_index:
  directory:
    - inc
provides:
  Perl::Build:
    file: lib/Perl/Build.pm
    version: 0.03
requires:
  CPAN::Perl::Releases: 0
  Devel::PatchPerl: 0
  File::pushd: 0
  perl: 5.008005
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
