---
abstract: 'perl builder'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Build
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Perl::Build:
    file: lib/Perl/Build.pm
    version: 1.04
  Perl::Build::Built:
    file: lib/Perl/Build/Built.pm
    version: 1.04
requires:
  CPAN::Perl::Releases: 0
  Devel::PatchPerl: 0.88
  File::Temp: 0
  File::pushd: 0
  Getopt::Long: 0
  HTTP::Tiny: 0
  Pod::Usage: 0
  perl: 5.008002
resources:
  bugtracker: https://github.com/tokuhirom/Perl-Build/issues
  homepage: https://github.com/tokuhirom/Perl-Build
  repository: git://github.com/tokuhirom/Perl-Build.git
version: 1.04
x_contributors:
  - 'Daisuke Murase <typester@cpan.org>'
  - 'Kent Fredric <kentfredric@gmail.com>'
  - 'Mark Stosberg <mark@stosberg.com>'
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'Kang-min Liu <gugod@gugod.org>'
  - 'Akihiro Uchida <uchida@ike-dyn.ritsumei.ac.jp>'
