---
abstract: 'perl builder'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Build
provides:
  Perl::Build:
    file: lib/Perl/Build.pm
    version: 0.15
requires:
  CPAN::Perl::Releases: 0
  Devel::PatchPerl: 0.84
  File::pushd: 0
  HTTP::Tiny: 0
  perl: 5.008002
resources:
  bugtracker: https://github.com/tokuhirom/Perl-Build/issues
  homepage: https://github.com/tokuhirom/Perl-Build
  repository: git://github.com/tokuhirom/Perl-Build.git
version: 0.15
x_contributors:
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'Daisuke Murase <typester@cpan.org>'
  - 'Mark Stosberg <mark@stosberg.com>'
